In [14]:
import numpy as np

# Coefficient matrix A (5x5 matrix)
A = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

# Constant matrix B (5x1 matrix)
B = np.array([100, 150, 120, 110, 140])

# Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)


Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


Problem 1: Solve the system of linear equations using matrix inversion

In [25]:
# Matrix A1 (coefficients)
A1 = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]])

# Matrix B1 (constants)
B1 = np.array([5, 6, 7])

# Check if A1 has an inverse
det_A1 = np.linalg.det(A1)
if det_A1 == 0:
    print("A1 can't be inverted!")
else:
    # Find the inverse of A1
    A1_inv = np.linalg.inv(A1)
    # Solve for X
    X1 = np.dot(A1_inv, B1)
    print("Solution for Problem 1:")
    print(X1)

Solution for Problem 1:
[2.64102564 1.61538462 1.8974359 ]


Problem 2: Solve the network of computers system

In [26]:
# Matrix A2 (coefficients)
A2 = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

# Matrix B2 (constants)
B2 = np.array([200, 300, 150, 120, 250])

# Check if A2 has an inverse
det_A2 = np.linalg.det(A2)
if det_A2 == 0:
    print("A2 can't be inverted!")
else:
    # Find the inverse of A2
    A2_inv = np.linalg.inv(A2)
    # Solve for X
    X2 = np.dot(A2_inv, B2)
    print("Solution for Problem 2:")
    print(X2)

Solution for Problem 2:
[ -23.86666667  137.6        -336.          242.53333333  241.86666667]


Problem 3: Solve for 7 unknown variables in a cryptographic algorithm

In [39]:
# Matrix A3 (random 7x7 coefficients)
A3 = np.random.rand(7, 7)

# Matrix B3 (random 7x1 constants)
B3 = np.random.rand(7)

# Check if A3 has an inverse
det_A3 = np.linalg.det(A3)
if det_A3 == 0:
    print("A3 can't be inverted!")
else:
    # Find the inverse of A3
    A3_inv = np.linalg.inv(A3)
    # Solve for X
    X3 = np.dot(A3_inv, B3)
    print("Solution for Problem 3:")
    print(X3)

Solution for Problem 3:
[ 0.20091141 -1.79944651  2.27447131  2.49518308  0.08444156 -2.45914623
 -0.77710437]


Problem 4: Solve for 5 unknowns in a machine component system

In [36]:
# Matrix A4 (random 5x5 coefficients)
A4 = np.random.rand(5, 5)

# Matrix B4 (random 5x1 constants)
B4 = np.random.rand(5)

# Check if A4 has an inverse
det_A4 = np.linalg.det(A4)
if det_A4 == 0:
    print("A4 can't be inverted!")
else:
    # Find the inverse of A4
    A4_inv = np.linalg.inv(A4)
    # Solve for X
    X4 = np.dot(A4_inv, B4)
    print("Solution for Problem 4:")
    print(X4)

Solution for Problem 4:
[ 6.84190097 -8.86309595  8.40672232 -1.61770714 -4.45193383]


Problem 5: Write a Python function to solve for any number of unknowns using matrix inversion

In [40]:
def solve_linear_system(A, B):
    det_A = np.linalg.det(A)
    if det_A == 0:
        print("Matrix A is singular and cannot be inverted!")
        return None
    else:
        A_inv = np.linalg.inv(A)
        X = np.dot(A_inv, B)
        return X

A5 = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

B5 = np.array([100, 150, 120, 110, 140])

solution = solve_linear_system(A5, B5)
if solution is not None:
    print("Solution for Problem 5 (Unknowns):")
    print(solution)

Solution for Problem 5 (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]
