In [1]:
import numpy as np

# Step 1: Define the 3x4 augmented matrix
matrix_3x4 = np.array([
    [15, 2, 6, 19],
    [17, 1, 13, 19],
    [16, 11, 13, 13]
], dtype=float)

# Separate Coefficient Matrix (A) and Right-hand Side Vector (b)
A = matrix_3x4[:, :3]  # Coefficient matrix
b = matrix_3x4[:, 3]   # RHS vector

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

# --- Matrix Inverse Method ---
print("\n--- Matrix Inverse Method Steps ---")

try:
    # Step 1: Compute the determinant of A
    det_A = np.linalg.det(A)
    print(f"Determinant of A: {det_A:.4f}")

    if det_A == 0:
        raise ValueError("Matrix A is singular and cannot be inverted.")

    # Step 2: Compute the adjugate of A manually
    adj_A = np.zeros_like(A)

    # Calculate minors and cofactors manually for each element of A
    adj_A[0, 0] =  A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]  # Minor of A[0, 0]
    adj_A[0, 1] = -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0])  # Minor of A[0, 1]
    adj_A[0, 2] =  A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]  # Minor of A[0, 2]

    adj_A[1, 0] = -(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1])  # Minor of A[1, 0]
    adj_A[1, 1] =  A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]  # Minor of A[1, 1]
    adj_A[1, 2] = -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])  # Minor of A[1, 2]

    adj_A[2, 0] =  A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]  # Minor of A[2, 0]
    adj_A[2, 1] = -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0])  # Minor of A[2, 1]
    adj_A[2, 2] =  A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]  # Minor of A[2, 2]

    print("Adjugate of A (before transpose):\n", adj_A)

    # Step 3: Transpose the adjugate to get the cofactor matrix
    adj_A = adj_A.T
    print("Cofactor Matrix (Adjugate Transposed):\n", adj_A)

    # Step 4: Compute the inverse using A_inv = adj(A) / det(A)
    A_inv = adj_A / det_A
    print("Inverse of A:\n", A_inv)

    # Step 5: Compute the solution x = A^-1 * b
    x_inverse = np.dot(A_inv, b)
    print("\nSolution using Matrix Inverse Method:")
    print(f"x = {x_inverse[0]:.4f}, y = {x_inverse[1]:.4f}, z = {x_inverse[2]:.4f}")
except ValueError as e:
    print(e)
except np.linalg.LinAlgError:
    print("Matrix A is singular and cannot be inverted.")

# --- Gaussian Elimination ---
print("\n--- Gaussian Elimination Steps ---")

# Convert to Augmented Matrix [A|b]
aug_matrix = np.hstack((A, b.reshape(-1, 1)))
print("Initial Augmented Matrix [A|b]:\n", aug_matrix)

# Step 1: Eliminate first column below the pivot (Row 1)
print("\nEliminating entries below pivot in the first column...")

r1 = aug_matrix[0]  # Row 1
r2 = aug_matrix[1]  # Row 2
r3 = aug_matrix[2]  # Row 3

# Multiplier for Row 2 and Row 3
m21 = r2[0] / r1[0]
m31 = r3[0] / r1[0]

# Row operations
r2 = r2 - m21 * r1
r3 = r3 - m31 * r1

# Update the matrix
aug_matrix[1] = r2
aug_matrix[2] = r3
print("Augmented Matrix after eliminating first column:\n", aug_matrix)

# Step 2: Eliminate second column below the pivot (Row 2)
print("\nEliminating entries below pivot in the second column...")

r2 = aug_matrix[1]  # Updated Row 2
r3 = aug_matrix[2]  # Updated Row 3

# Multiplier for Row 3
m32 = r3[1] / r2[1]

# Row operation
r3 = r3 - m32 * r2

# Update the matrix
aug_matrix[2] = r3
print("Augmented Matrix after eliminating second column:\n", aug_matrix)

# Step 3: Normalize the rows (make pivots equal to 1)
print("\nNormalizing pivots to 1...")

aug_matrix[0] = aug_matrix[0] / aug_matrix[0][0]
aug_matrix[1] = aug_matrix[1] / aug_matrix[1][1]
aug_matrix[2] = aug_matrix[2] / aug_matrix[2][2]

print("Normalized Augmented Matrix:\n", aug_matrix)

# Step 4: Back Substitution to solve for x, y, z
print("\n--- Back Substitution ---")

z = aug_matrix[2, 3]
y = aug_matrix[1, 3] - aug_matrix[1, 2] * z
x = aug_matrix[0, 3] - aug_matrix[0, 2] * z - aug_matrix[0, 1] * y

print(f"z = {z}")
print(f"y = {y}")
print(f"x = {x}")

# --- Verification ---
print("\n--- Verification ---")

# Verification for Matrix Inverse Method
b_check_inverse = np.dot(A, x_inverse)
print("Verification for Matrix Inverse Method (Ax):\n", b_check_inverse)

# Verification for Gaussian Elimination
solution_gaussian = np.array([x, y, z])
b_check_gaussian = np.dot(A, solution_gaussian)

print("Verification for Gaussian Elimination (Ax):\n", b_check_gaussian)
print("Original b:\n", b)

# Confirm both solutions satisfy Ax = b
if np.allclose(b, b_check_inverse) and np.allclose(b, b_check_gaussian):
    print("\nBoth solutions satisfy Ax = b. Verified!")
else:
    print("\nOne or both solutions do not satisfy Ax = b. Check calculations.")

Generated 3x4 Matrix:
[[15.  2.  6. 19.]
 [17.  1. 13. 19.]
 [16. 11. 13. 13.]]

Coefficient Matrix (A):
[[15.  2.  6.]
 [17.  1. 13.]
 [16. 11. 13.]]

Right-hand Side Vector (b):
[19. 19. 13.]

--- Matrix Inverse Method Steps ---
Determinant of A: -950.0000
Adjugate of A (before transpose):
 [[-130.  -13.  171.]
 [  40.   99. -133.]
 [  20.  -93.  -19.]]
Cofactor Matrix (Adjugate Transposed):
 [[-130.   40.   20.]
 [ -13.   99.  -93.]
 [ 171. -133.  -19.]]
Inverse of A:
 [[ 0.13684211 -0.04210526 -0.02105263]
 [ 0.01368421 -0.10421053  0.09789474]
 [-0.18        0.14        0.02      ]]

Solution using Matrix Inverse Method:
x = 1.5263, y = -0.4474, z = -0.5000

--- Gaussian Elimination Steps ---
Initial Augmented Matrix [A|b]:
 [[15.  2.  6. 19.]
 [17.  1. 13. 19.]
 [16. 11. 13. 13.]]

Eliminating entries below pivot in the first column...
Augmented Matrix after eliminating first column:
 [[15.          2.          6.         19.        ]
 [ 0.         -1.26666667  6.2        -2.5333