Problem 1: Find the inverse of the matrix

Given matrix A = [[3, 4], let's find its inverse.
                  [2, 5]]

In [38]:
import numpy as np  # Import the NumPy library for numerical operations

# Define the 2x2 matrix
A = np.array([[3, 4],  # First row of the matrix
              [2, 5]])  # Second row of the matrix

# Calculate the determinant of the matrix
det_A = np.linalg.det(A)  # Use NumPy to find the determinant
print(f"Determinant of A: \n{det_A}")  # Print the determinant

if det_A != 0:  # Check if the determinant is not zero (matrix is invertible)
    # Calculate the inverse of the matrix
    A_inv = np.linalg.inv(A)  # Use NumPy to find the inverse
    print("\nInverse of A:")  # Print a message
    print(A_inv)  # Print the inverse matrix
else:
    print("Matrix A is not invertible.")  # Print a message if the matrix is not invertible

Determinant of A: 
7.000000000000001

Inverse of A:
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


Problem 2: Solve the system of equations

The system is: 
                
      {2x + 3y = 7}
      {4x - y = 5}

In [39]:
# Coefficient matrix
coef = np.array([[2, 3],  # First row of the coefficient matrix
                 [4, -1]])  # Second row of the coefficient matrix

# Constant vector
rhs_matrix = np.array([7, 5])  # Right-hand side constants of the equations

# Check if the coefficient matrix is invertible
if np.linalg.det(coef) != 0:  # Check if the determinant is not zero (matrix is invertible)
    # Solve for [x, y] using the matrix inverse
    solution = np.linalg.inv(coef).dot(rhs_matrix)  # Find the solution using the inverse
    print("Solution for [x and y]:")  # Print a message
    print("x =", solution[0], ", y =", solution[1])  # Print the values of x and y
else:
    print("Matrix coefficient is not invertible, no unique solution.")  # Print a message if the matrix is not invertible


Solution for [x and y]:
x = 1.5714285714285716 , y = 1.2857142857142858


Problem 3: Analyze the matrix

Matrix A = 
    
    [[1, 2, 3]
    [0, 1, 4]
    [5, 6, 0]]

Tasks:
- Check if the matrix is invertible.
- Find its determinant.
- If invertible, calculate the inverse.

In [41]:
# Define the 3x3 matrix
A = np.array([[1, 2, 3],  # First row of the matrix
              [0, 1, 4],  # Second row of the matrix
              [5, 6, 0]])  # Third row of the matrix

# Calculate the determinant of the matrix
det_A = np.linalg.det(A)  # Use NumPy to find the determinant
print(f"Determinant of A: \n{det_A}")  # Print the determinant

if det_A != 0:  # Check if the determinant is not zero (matrix is invertible)
    # Calculate the inverse of the matrix
    A_inverse = np.linalg.inv(A)  # Use NumPy to find the inverse
    print("\nInverse of A:")  # Print a message
    print(A_inverse)  # Print the inverse matrix
else:
    print("Matrix A is not invertible.")  # Print a message if the matrix is not invertible

Determinant of A: 
0.9999999999999964

Inverse of A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


Problem 4: Solve the system of equations using matrix inverse

System of Equations:

x+y+z =6
2x+5y+z =−4
2x+3y+8z =9
​

In matrix form:

    A = [[1, 1, 1]
         [2, 5, 1] 
         [2, 5, 1]
         [2, 3, 8]]

    b = [[6]
        [-4] 
        [9]]

In [43]:
# Coefficient matrix
A = np.array([[1, 1, 1],  # First row of the coefficient matrix
              [2, 5, 1],  # Second row of the coefficient matrix
              [2, 3, 8]])  # Third row of the coefficient matrix

# Constant vector
b = np.array([6, -4, 9])  # Right-hand side constants of the equations

# Check if A is invertible
det_A = np.linalg.det(A)  # Use NumPy to find the determinant
print(f"Determinant of A: \n{det_A}")  # Print the determinant

if det_A != 0:  # Check if the determinant is not zero (matrix is invertible)
    # Compute the inverse and solve for x
    A_inv = np.linalg.inv(A)  # Use NumPy to find the inverse
    x = A_inv.dot(b)  # Find the solution using the inverse
    print("\nSolution for [x, y, z]:")  # Print a message
    print(x)  # Print the values of x, y, and z
else:
    print("\nMatrix A is not invertible.")  # Print a message if the matrix is not invertible

Determinant of A: 
18.999999999999996

Solution for [x, y, z]:
[10.84210526 -5.21052632  0.36842105]


Problem 5: A system of linear equations is given by the following matrix equation

Where: 

    A = [[4, -1, 0]
         [3, 5, 2]
         [-2, 4, 1]]

    b = [[5]
        [6] 
        [2]]

In [44]:
# Coefficient matrix
A = np.array([[4, -1, 0],
              [3, 5, 2],
              [-2, 4, 1]])

# Constant vector
b = np.array([5, 6, 2])

# Check if A is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: \n{det_A}")

if det_A != 0:
    # Compute the inverse and solve for x
    A_inv = np.linalg.inv(A)
    x = A_inv.dot(b)
    print("\nSolution for [x1, x2, x3]:")
    print(x)
else:
    print("\nMatrix A is not invertible.")


Determinant of A: 
-5.000000000000002

Solution for [x1, x2, x3]:
[  2.6   5.4 -14.4]
