In [28]:
import numpy as np

In [29]:
# Exercise 1: Matrix Addition & Subtraction
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("\nExercise 1 - Matrix Addition:")
print(matrix1 + matrix2)
print("\nExercise 1 - Matrix Subtraction:")
print(matrix1 - matrix2)


Exercise 1 - Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Exercise 1 - Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [30]:
# Exercise 2: Matrix Multiplication
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
matrix_B = np.array([[7, 8], [9, 10], [11, 12]])  # 3x2 matrix

# Perform matrix multiplication
mp_result = np.dot(matrix_A, matrix_B)
print("Exercise 2 - Matrix Multiplication:")
print(mp_result) 

Exercise 2 - Matrix Multiplication:
[[ 58  64]
 [139 154]]


In [31]:
# Define two matrices with the same shape for element-wise multiplication (2x2)
matrix_d = np.array([[2, 3], [4, 5]])
matrix_e = np.array([[6, 7], [8, 9]])

# Perform element-wise multiplication
elementwise_result = matrix_d * matrix_e
print("\nElement-Wise Multiplication (D * E):")
print(elementwise_result)

# Transpose of a matrix
transpose_result = matrix_d.T
print("\nTranspose of Matrix D:")
print(transpose_result) 


Element-Wise Multiplication (D * E):
[[12 21]
 [32 45]]

Transpose of Matrix D:
[[2 4]
 [3 5]]


In [32]:
# Exercise 3: Matrix Transpose
matrix3 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nExercise 3 - Transpose of Matrix:")
print(matrix3.T)

# Determinant of a Matrix
F = np.array([[4, 2], [3, 1]])
determinant_result = np.linalg.det(F)
print("\nDeterminant of F:", determinant_result)


Exercise 3 - Transpose of Matrix:
[[1 4]
 [2 5]
 [3 6]]

Determinant of F: -2.0


In [33]:
# Exercise 4: Calculating the Determinant
matrix4 = np.array([[1, 2, 1], 
                    [2, 3, 4], 
                    [3, 2, 5]])

print("\nExercise 4 - Determinant of 3x3 Matrix:")
print(np.linalg.det(matrix4))


Exercise 4 - Determinant of 3x3 Matrix:
6.000000000000003


In [34]:
# Exercise 5: Finding the Inverse
matrix5 = np.array([[1, 2], 
                    [3, 4]])

print("\nExercise 5 - Inverse of the 2x2 Matrix:")
print(np.linalg.inv(matrix5))



Exercise 5 - Inverse of the 2x2 Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
