### **Student Activity:** *Solving Rank of a Matrix, Systems of Equations, and Matrix Operations*

1. Rank of a Matrix
  
  The rank of a matrix can be determined using *numpy.linalg.matrix_rank*.

In [11]:
import numpy as np

# Define the matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the rank
rank = np.linalg.matrix_rank(A)

print(f"Rank of matrix A: {rank}")

Rank of matrix A: 2


2. Solving Systems of Equations Using Matrix Inverse (3x3)
  
    To solve systems of equations using the matrix inverse method, ensure the coefficient matrix is *invertible* (non-zero determinant).

In [12]:
import numpy as np

# Coefficient matrix
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Constant vector
b = np.array([8, -11, -3])

# Check if the determinant is non-zero (invertible matrix)
if np.linalg.det(A) != 0:
    # Solve for x using A^-1 * b
    x = np.linalg.inv(A).dot(b)
    print(f"Solution: {x}")
else:
    print("Matrix A is not invertible. No unique solution.")

Solution: [ 2.  3. -1.]


3. Matrix Addition for n×n Matrices

  Matrix addition is straightforward using *numpy*.

In [13]:
# Define two 4x4 matrices
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = np.array([[16, 15, 14, 13],
              [12, 11, 10, 9],
              [8, 7, 6, 5],
              [4, 3, 2, 1]])

# Add the matrices
C = A + B

print("Matrix A + B:")
print(C)

Matrix A + B:
[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]


# **Practice Problems**

Problem 1: Rank of a Matrix

In [14]:
# Define the matrix
A = np.array([[1, 2, 0, 4],
              [3, 6, 0, 8],
              [5, 10, 0, 12],
              [7, 14, 0, 16]])

# Compute the rank
rank = np.linalg.matrix_rank(A)

print(f"Rank of matrix A: {rank}")

Rank of matrix A: 2


Problem 2: Solve a 3x3 System of Equations

In [15]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[1, 1, 1],
              [2, 4, 3],
              [0, 0, 1]])

# Define the constant vector b
b = np.array([6, 18, 5])

# Check if the matrix A is invertible
if np.linalg.det(A) != 0:  # Determinant check for invertibility
    # Compute the solution X
    X = np.linalg.inv(A).dot(b)
    print(f"Solution: x = {X[0]}, y = {X[1]}, z = {X[2]}")
else:
    print("Matrix A is not invertible. No unique solution.")

Solution: x = 0.5, y = 0.5, z = 5.0


Problem 3: Solve a 4x4 System of Equations

In [16]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[1, 1, 1, 1],
              [2, 1, 0, 3],
              [4, 3, 2, 1],
              [3, 0, 5, 2]])

# Define the constant vector b
b = np.array([10, 11, 20, 15])

# Check if the matrix A is invertible
if np.linalg.det(A) != 0:  # Determinant check for invertibility
    # Compute the solution X
    X = np.linalg.inv(A).dot(b)
    print(f"Solution: {X[0]}, {X[1]}, {X[2]}, {X[3]}")
else:
    print("Matrix A is not invertible. No unique solution.")

Solution: -1.625, 6.0, 2.875, 2.75
