Section 1: Understanding Unary Operations

Q1: What are some examples of unary operations in matrices? Write your answer below:

Examples of unary operations in matrices:
1. Transpose - Flipping the matrix over its diagonal.
2. Trace - Summing up the diagonal elements of the matrix.
3. Determinant - Calculating a scalar value that describes the matrix's properties.


Section 1: Transpose of a Matrix and Symmetric Matrices


In [27]:
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Q2: Check if matrix_A is a symmetric matrix. Modify the code below to verify this.

In [28]:
# Check if the matrix is symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric? ", is_symmetric)


Is Matrix A symmetric?  False


Practice Problem 1: Create a 4x4 random matrix and check if it is symmetric.

In [29]:
# Your solution here
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

# Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)

Random Matrix:
 [[4 1 8 9]
 [5 6 4 1]
 [8 7 5 2]
 [7 3 5 5]]

Is the random matrix symmetric?  False


Section 2: Trace of a Matrix

In [30]:
# Calculate the trace of matrix_A
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)


Trace of Matrix A: 15


Q3: What is the trace of the following matrix?

In [31]:
# Your code here
matrix_B = np.array([[10, 20, 30],
                     [5, 15, 25],
                     [2, 4, 6]])

trace_B = np.trace(matrix_B)
print("\nTrace of Matrix B:", trace_B)


Trace of Matrix B: 31


Practice Problem 2: Find the trace of a 5x5 identity matrix.

In [32]:
# Your solution here
identity_matrix = np.identity(5)
trace_identity = np.trace(identity_matrix)
print("\nTrace of 5x5 Identity Matrix:", trace_identity)


Trace of 5x5 Identity Matrix: 5.0


Section 3: Determinant using the Cofactor Method

Practice Problem 3: Compute the determinant of the following 3x3 matrix using NumPy:

In [33]:
# Determinant using NumPy
det_A = np.linalg.det(matrix_A)
print("\nDeterminant of Matrix A:", det_A)


Determinant of Matrix A: 6.66133814775094e-16


Manual Cofactor Method

In [34]:
# Determinant of a 2x2 matrix using the cofactor method
matrix_C = np.array([[4, 6], [3, 8]])
det_C = (matrix_C[0, 0] * matrix_C[1, 1]) - (matrix_C[0, 1] * matrix_C[1, 0])
print("Determinant of Matrix C:", det_C)

Determinant of Matrix C: 14


Practice Problem 3: Compute the determinant of the following 3x3 matrix using NumPy:

In [35]:
# Your solution here
matrix_D = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

det_D = np.linalg.det(matrix_D)
print("\nDeterminant of Matrix D:", det_D)


Determinant of Matrix D: 6.66133814775094e-16


Section 4: Practice Problems

Practice Problem 4: Application in Computer Science

In [36]:
# Your solution here
random_matrix_3x3 = np.random.randint(0, 256, (3, 3))
transpose_3x3 = random_matrix_3x3.T
det_3x3 = np.linalg.det(random_matrix_3x3)

print("Random 3x3 Matrix representing pixel intensities:\n", random_matrix_3x3)
print("\nTranspose of the 3x3 Matrix:\n", transpose_3x3)
print("\nDeterminant of the 3x3 Matrix:", det_3x3)

Random 3x3 Matrix representing pixel intensities:
 [[ 21 149 192]
 [125 135  67]
 [ 31  51 245]]

Transpose of the 3x3 Matrix:
 [[ 21 125  31]
 [149 135  51]
 [192  67 245]]

Determinant of the 3x3 Matrix: -3210354.000000007


Practice Problem 5: Symmetric Matrices in Machine Learning

In [37]:
# Your solution here
symmetric_matrix = np.array([[2, 3, 4],
                             [3, 5, 6],
                             [4, 6, 8]])

# Verify if the matrix is symmetric
is_symmetric_matrix = (symmetric_matrix == symmetric_matrix.T).all()
print("Symmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric? ", is_symmetric_matrix)

Symmetric Matrix:
 [[2 3 4]
 [3 5 6]
 [4 6 8]]

Is the matrix symmetric?  True
